config/routes.rb
Rails.application.routes.draw do
  resources :relay_results
  resources :entries do
    member do
      patch :confirm
      delete :reject
      patch :pending
    end
  end
  post 'results/from_competition'
  resources :results
  get 'runners/license'
  get 'runners/update_profile', to: 'runners#update_profile'

  resources :runners do
    collection do
      post 'license'
    end

    member do
      post :merge
    end
  end
  resources :clubs do
       member do
      post :merge
    end
  end

  get 'categories/expired', to: 'categories#expired'
  resources :categories

  get 'groups/pdf'

  resources :groups
  devise_for :users
  get 'competitions/ecn_ranking'
  resources :competitions do
    member do
      get 'pdf', to: 'competitions#pdf'
      get 'group_clasa', to: 'competitions#group_clasa'
      get 'new_runners', to: 'competitions#new_runners'
      post 'set_ecn', as: 'set_ecn'
      get 'group_ecn_coeficients', to: 'competitions#group_ecn_coeficients'
      post 'group_ecn_coeficients', to: 'competitions#update_group_ecn_coeficients', as: 'update_group_ecn_coeficients'
      post 'group_clasa', to: 'competitions#update_group_clasa', as: 'update_group_clasa'
      get 'ecn_csv', to: 'competitions#ecn_csv', as: 'download_ecn_csv'
      get 'set_wre_categories', to: 'competitions#set_wre_categories', as: 'set_wre_categories'
    end
  end

  get 'home/index'
  post 'result/modal_new', to: 'results#modal_new', as: "modal_result"

  root "home#index"
  get 'parser/index', as: "parser"
  get 'parser/file_results', as: 'file_results'
  post 'parser/file_results'
  post 'parser/file_relay_results'
  post 'parser/runners_dob'
  get 'parser/iof_runners', as: 'iof_runners'
  get 'parser/iof_results', as: 'iof_results'
  get 'parser/fos_data', as: 'fos_data'
  get 'parser/sync_fos', as: 'sync_fos'
  post 'groups/count_rang', as: 'count_rang'
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :groups , dependent: :destroy
  accepts_nested_attributes_for :groups

  before_save :add_checksum

  def add_checksum
    self.checksum = (Digest::SHA2.new << "#{self.competition_name}-#{self.date.as_json}-#{self.distance_type}-#{self.wre_id}").to_s
  end

  def self.get_checksum(competition_name, date, distance_type, wre_id)
    (Digest::SHA2.new << "#{competition_name}-#{date.as_json}-#{distance_type}-#{wre_id}").to_s
  end

  def self.find_competition(params)
    Competition.find_by(checksum: get_checksum(*params.values_at("competition_name", "date", "distance_type", "wre_id")))
  end

  def self.add_competition(params)
    params = params.with_indifferent_access

    competition = Competition.find_by(wre_id: params["wre_id"]) if params["wre_id"]
    competition ||= Competition.find(params["competition_id"]) if params["competition_id"]

    checksum = get_checksum(*params.values_at("competition_name", "date", "distance_type", "wre_id"))

    competition ||= Competition.find_or_create_by(checksum: checksum) do |comp|
       comp.competition_name = params[:competition_name]
       comp.date             = params[:date]
       comp.distance_type    = params[:distance_type]
       comp.location         = params[:location]
       comp.country          = params[:country]
       comp.wre_id           = params[:wre_id]
     end
  end

  def relay?
    distance_type.match?(/stafeta/i)
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: %i[show edit update destroy group_clasa update_group_clasa group_ecn_coeficients set_ecn update_group_ecn_coeficients new_runners pdf ecn_csv set_wre_categories]

  # GET /competitions or /competitions.json
  def index
    @competitions = Competition.all

    @competitions = @competitions.where.not(wre_id: nil) if params[:wre]
    @competitions = @competitions.where(distance_type: params[:distance_type]) if params[:distance_type].present?
    if params[:country].present?
      @competitions = if params[:country] == 'Internationale'
                        @competitions.where.not(country: 'Moldova')
                      else
                        @competitions.where(country: params[:country])
                      end
    end

    if params[:date_from].present? || params[:date_to].present?
      date_from = Date.parse(params[:date_from]) if params[:date_from].presence
      date_to = Date.parse(params[:date_to]) if params[:date_to].presence
      @competitions = @competitions.where(date: date_from..date_to)
    end

    if params[:sort_by].present?
      direction = params[:direction] == 'desc' ? 'desc' : 'asc'
      @competitions = @competitions.order(params[:sort_by] => direction)
    end
    if params[:search].present?
      @competitions = @competitions.where(' LOWER(competition_name) LIKE :search',
                                          search: "%#{params[:search].downcase}%")
    end

    @competitions = @competitions.order(date: :desc).paginate(page: params[:page], per_page: 10)
  end

  # GET /competitions/1 or /competitions/1.json
  def show; end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  def pdf
    respond_to do |format|
      format.html do
        layout = @competition.relay? ? "pdf_relay" : "pdf"
        render pdf: "competitions/#{@competition.id}",
               template: 'competitions/show',
               layout: layout,
               formats: [:html]
      end
    end
  end

  # GET /competitions/1/edit
  def edit; end

  # POST /competitions or /competitions.json
  def create
    respond_to do |format|
      parser = CompetitionFormParser.new(competition_params)
      @competition = parser.convert

      format.html { redirect_to competition_url(@competition), notice: 'Competitia a fost creata cu succes' }
      format.json { render :show, status: :created, location: @competition }
    end
  end

  # PATCH/PUT /competitions/1 or /competitions/1.json
  def update
    remove_groups
    add_groups

    respond_to do |format|
      if @competition.update(competition_params.except(:group_list))
        format.html { redirect_to competition_url(@competition), notice: 'Competitia a fost actualizata' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1 or /competitions/1.json
  def destroy
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def group_clasa; end

  def group_ecn_coeficients; end

  def update_group_clasa
    check_exprired_cagegories
    results = Result.joins(:group).where("group.competition_id": @competition.id).update_all(category_id: 10)

    @competition.update(group_clasa_params)

    @competition.groups.each do |group|
      next if group.results.blank?
      parser = if @competition.distance_type&.include?("Stafeta")
        RelayGroupCategoriesUpdater
      else
        GroupCategoriesUpdater
      end.new(group).get_rang_and_categories
    end

    redirect_to competition_url(@competition)
  end

   def set_wre_categories
    check_exprired_cagegories
    results = Result.joins(:group).where("group.competition_id": @competition.id)
    results.update_all(category_id: 10)
    results.each do |result|
      category_id = get_wre_category(result)
      ResultAndEntryProcessor.new({category_id: category_id}, result, nil, get_status(category_id, result.runner)).update_result
    end

    redirect_to competition_url(@competition)
  end

  def set_ecn
    @competition.update(ecn: !@competition.ecn)

    unless @competition.ecn
      @competition.groups.each do |group|
        group.ecn_coeficient = 0.0
        group.results.each do |result|
          result.ecn_points = 0.0
        end
      end
    end

    redirect_to competition_url(@competition)
  end

  def update_group_ecn_coeficients
    @competition.update(group_ecn_coeficients_params)

    @competition.groups.each do |group|
      next if group.ecn_coeficient.zero?

      winner_time = group.results.order(:place).first.time
      coeficient  = group.ecn_coeficient

      group.results.each do |result|
        ecn_points = (coeficient * winner_time / result.time * 100).round(2)
        ResultAndEntryProcessor.new( { ecn_points: ecn_points }, result ).update_result
      end
    end

    redirect_to competition_url(@competition)
  end

  def ecn_ranking
    respond_to do |format|
      format.html do
        @year = params[:year] || Time.now.year
        gender = params[:gender].presence || 'M'

        @runners = if params[:year].to_i == 2024
          ranking_2024(gender)
        else
          ranking_2025(gender)
        end

        @runners = @runners.select { |rn| rn.total_points > 0 }
      end

      format.json do
        limit = params[:size] || 20
        hash = {}
        data = ["M", "W"].each do |gender|
          runners = Runner.where(gender:).joins(:results, :club)
                         .where('results.ecn_points > 0')
                         .group('runners.id, clubs.club_name')
                         .order('SUM(results.ecn_points) DESC')
                         .select('runners.id, runners.runner_name, runners.surname, runners.dob, runners.club_id, runners.gender,
                          clubs.club_name,
                          ROUND(SUM(results.ecn_points)::numeric, 2) AS total_points, COUNT(results.ecn_points) AS ecn_results_count,
                          RANK() OVER (ORDER BY SUM(results.ecn_points) DESC) AS place').limit( limit)
            runner_gender = gender == "M" ? "Masculin" : "Femenin"
            hash[runner_gender] = runners
          end

        render json: hash
      end
    end
  end

  def new_runners
    @all_runners = Runner.all

    @runners = Runner.where(created_at: @competition.created_at..@competition.created_at + 10.minutes).includes(:club)
  end

  def ecn_csv
    csv_data = generate_competition_csv
    send_data csv_data, filename: "competition_results.csv", type: "text/csv"
  end

  def generate_competition_csv
    CSV.generate(col_sep: ",") do |csv|
    # Add the header rows
      csv << ["Denumirea Competiției", "", "", "", "", "", "", "", "Parola", "Lasm1177Unasm"]
      csv << [@competition.competition_name, "", "", "", "", "", "", "", "", ""]
      csv << ["Locație", "", "", "", "", "", "", "", "", ""]
      csv << [@competition.location, "", "", "", "", "", "", "", "", ""]
      csv << ["Data", "", "Tipul", "Trasator", "", "", "Organizator", "", "", ""]
      csv << [@competition.date, "", @competition.distance_type, "", "", "", "", "", "", ""]

      @competition.groups.each do |group|
        csv << ["", "", "", "", "", "", "", "", "", ""]

        csv << ["Categorie", group.group_name, "Lungime", "", "Nr. PC", "", "Coeficient", group.ecn_coeficient, "Rang", group.rang, "Clasa", Category.find(group.clasa.to_i).category_name, "Campionat Național", "", ""]
        csv << ["ID", "Loc", "Nume, Prenume", "Cat. sportivă", "Rezultat", "Cat. îndeplinită", "Club", "Country", "", "", ""]
        group.results.each do |result|
         @default_category ||= Category.find(10)
          current_category = (result.runner.entry_on_date(result.date)&.category || @default_category).category_name

        csv << [result.runner.id, result.place, "#{result.runner.runner_name} #{result.runner.surname}", current_category, Time.at(result.time).utc.strftime('%H:%M:%S'), result.category.category_name, result.runner.club.club_name, "", "", "", ""]
      end
    end

    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_competition
    @competition = Competition.find(params[:id])
  end

  def add_groups
    return if competition_params[:group_list].blank?

    group_names = competition_params[:group_list].split(',').map(&:strip)
    Group.add_groups(group_names, @competition)
  end

  def remove_groups
    return if competition_params[:group_list].blank?

    group_names = @competition.groups.pluck(:group_name) - competition_params[:group_list].split(',').map(&:strip)
    Group.delete_groups(group_names, @competition)
  end

  # Only allow a list of trusted parameters through.
  def competition_params
    params.require(:competition).permit(:competition_name, :date, :location, :country, :distance_type, :wre_id, :checksum, :group_list, :size)
  end

  def group_clasa_params
    params.require(:competition).permit(groups_attributes: %i[id clasa])
  end

  def group_ecn_coeficients_params
    params.require(:competition).permit(groups_attributes: %i[id ecn_coeficient])
  end

  def check_exprired_cagegories
    Runner.where('category_valid < ?', @competition.date).each do |runner|
      category_id =  runner.category_id == 6 && (Date.today.year - runner.dob.year > 19) ? 10 : runner.category_id + 1
      ResultAndEntryProcessor.new({ runner_id: runner.id, category_id: category_id, date: runner.category_valid, group_id: 2}, nil, nil, Entry::CONFIRMED).add_result
    end
  end

  def get_wre_category(result)
    delta = result.date < "01.01.2024".to_date ? 50 : 0

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form2.html.erb
<%= form_with url: modal_competition_path, method: :post, remote: true, id: 'competitionForm' do |f| %>

<div class="row">
    <div class="col">
        <%= f.text_field :competition_name, placeholder: "Numele Competitiei", class: "form-control"  %>
    </div>
    <div class="col">
        <%= f.text_field :distance_type, placeholder: "Tipul Distantei", class: "form-control"  %>
    </div>
    <div class="col">
        <%= form.text_field :wre_id, placeholder: "WRE ID", class: "form-control"  %>
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <%= f.label :date ,'Data'%>
        <%= f.date_select :date, class: "form-control"%>
    </div>
</div>
<br>
<div class="row">
    <div class="col">
        <%= f.text_field :location, placeholder: "Localitatea", class: "form-control"  %>
    </div>
    <div class="col">
        <%= f.text_field :country, placeholder: "Tara", class: "form-control"  %>
    </div>
</div>
<br>
 <div class="actions">
    <%= f.submit "Crează Competiție", class: "btn btn-success btn-sm"%>
    <%= link_to 'Inapoi', request.referer, class: "btn btn-secondary btn-sm" %>
</div>
<% end %>

app/views/competitions/ecn_ranking.html.erb
<%= link_to "Masculin", "#{competitions_ecn_ranking_path}?gender=M", class: "btn btn-info" %>
<%= link_to "Feminin", "#{competitions_ecn_ranking_path}?gender=W", class: "btn btn-info" %>
<table class="table table-striped table-bordered table-hover" id="runners-table">
    <thead class="table-primary">
        <tr>
            <th scope="col" class="sortable" data-sort-by="place">
                <%= link_to 'Place' %>
            </th>
            <th class="sortable" data-sort-by="id">
                <%= link_to 'FOS ID' %>
            </th>
            <th class="sortable" data-sort-by="runner">
                <%= link_to 'Nume' %>
            </th>
            <th class="sortable" data-sort-by="gender">
                <%= link_to 'Genul' %>
            </th>
            <th class="sortable" data-sort-by="dob">
                <%= link_to 'Data Nastere'%>
            </th>
            <th class="sortable" data-sort-by="club">
                <%= link_to 'Club' %>
            </th>
            <th class="sortable" data-sort-by="ecn_points">
                <%= link_to 'ECN Puncte' %>
            </th>
            <th class="sortable" data-sort-by="ecn_points">
                <%= link_to 'ECN Competitii' %>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @runners.each_with_index do |runner, index| %>
        <tr data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="false" aria-controls="collapse<%= index %>">
            <td>
                <%= index + 1 %>
            </td>
            <td>
                <%= runner.id %>
            </td>
            <td>
                <%= link_to "#{runner.runner_name} #{runner.surname}", runner %>
            </td>
            <td>
                <%= runner.gender %>
            </td>
            <td>
                <%= runner.dob.strftime("%d/%m/%Y") %>
            </td>
            <td>
                <%= link_to runner.club&.club_name, runner.club %>
            </td>
            <td>
                <%= runner.total_points.round(2) %>
            </td>
            <td>
                <%= runner.ecn_results_count.round(2) %>
            </td>
            <td class="text-center">
                <i class="bi bi-chevron-down toggle-icon" style="font-size: 20px">&#11021;</i>
            </td>
        </tr>
        <tr id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= index %>">
            <td colspan="9">
                <div class="accordion-body">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Data</th>
                                <th>Competitia</th>
                                <th>Grupa</th>
                                <th>Locul</th>
                                <th>Puncte</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% runner.results.where('ecn_points > 0').where('date > ?', "01-01-#{@year}".to_date).order(date: :desc).each do |result| %>
                            <tr>
                                <td>
                                    <%= result.date.strftime("%d/%m/%Y") %>
                                </td>
                                <td>
                                    <%= link_to result.group.competition.competition_name, result.group.competition %>
                                </td>
                                <td>
                                    <%= result.group.group_name %>
                                </td>
                                <td>
                                    <%= result.place %>
                                </td>
                                <td>
                                    <%= result.ecn_points %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/competitions/edit.html.erb
<h1>Editeaza Competitia</h1>

<%= render 'form', competition: @competition %>

app/views/competitions/index.html.erb
<p id="notice">
    <%= notice %>
</p>
<div class="container mt-4">
    <h1 class="mb-4" style="text-align:center; color:green">Competiții</h1>
    <%= form_tag competitions_path, method: :get, id: 'competitions_search_form' do %>
    <%= text_field_tag :search, params[:search], id: 'search', placeholder: "Cauta dupa Denumirea Competitiei", class: "form-control mb-2"%>
    <%= submit_tag "Cauta", class: "btn btn-info" %>
    <hr>
    <%= label_tag "country", "Tara", class: "label-filter" %>
    <%= select_tag :country, options_for_select(["Internationale"] + all_countries), include_blank: "Toate", class: "custom-select" %>
    <br>
    <%= label_tag "distance_type", "Tipul Distantei", class: "label-filter" %>
    <%= select_tag :distance_type, options_for_select(["Sprint", "Medie", "Lunga", "Alegere", "Sprint Stafeta", "Stafeta", "Knock Out Sprint", "Alta"], params[:distance_type]), include_blank: "Toate Tipurile",class: "custom-select" %>
    <br>
    <%= label_tag "wre", "WRE",class: "label-filter" %>
    <%= check_box_tag :wre, 1, params[:wre], id: "wre" %>
    <br>
    <%= label_tag "date_from", "Data: De la", class: "label-filter" %>
    <%= text_field_tag :date_from, params[:date_from] , id: 'date_from', placeholder: "zz/ll/aaaa", class: "datepicker custom-select" %>
    <%= label_tag "date_to", "Pina la" %>
    <%= text_field_tag :date_to, params[:date_to], id: 'date_to', placeholder: "zz/ll/aaaa", class: "datepicker custom-select" %>
    <br>
    <%= submit_tag "Filtreaza", class: "btn btn-info" %>
    <% end %>
    <table class="table table-bordered table-hover table-striped" id="competitions-table">
        <thead class="table-primary">
            <tr>
                <th scope="col" class="sortable" data-sort-by="date">
                    <%= link_to 'Data' %>
                </th>
                <th class="sortable" data-sort-by="competition_name">
                    <%= link_to 'Nume'%>
                </th>
                <th class="sortable" data-sort-by="location">
                    <%= link_to 'Oras'%>
                </th>
                <th class="sortable" data-sort-by="country">
                    <%= link_to 'Tara'%>
                </th>
                <th class="sortable" data-sort-by="distance_type">
                    <%= link_to 'Tipul distantei'%>
                </th>
                <th class="sortable" data-sort-by="wre_id">
                    <%= link_to 'Wre ID'%>
                </th>
                <th colspan="3">Acțiuni</th>
            </tr>
        </thead>
        <div class="py-4">
        </div>
        <tbody>
            <% @competitions.each do |competition| %>
            <tr>
                <td>
                    <%= competition.date %>
                </td>
                <td>
                    <%= link_to competition.competition_name, competition %>
                </td>
                <td>
                    <%= competition.location %>
                </td>
                <td>
                    <%= competition.country %>
                </td>
                <td>
                    <%= competition.distance_type %>
                </td>
                <td>
                    <%= competition.wre_id %>
                </td>
                <td>
                    <%= link_to 'Arată', competition, class: "btn btn-warning btn-sm"%>
                </td>
                <% if admin_user? %>
                <td>
                    <%= link_to 'Editează', edit_polymorphic_path(competition), class: "btn btn-success btn-sm"%>
                </td>
                <td>
                    <%= link_to 'Șterge', competition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
        <div class="pagination">
            <%= will_paginate @competitions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        </div>
    </table>
    <% if admin_user? %>
    <%= link_to 'Competitie Noua', new_competition_path, class: "btn btn-info" %>
    <% end %>
</div>

app/views/competitions/new.html.erb
<h1>Competititie Noua</h1>

<%= render 'form', competition: @competition %>

app/views/competitions/new_runners.html.erb
    <%= link_to 'Competitia', competition_path(@competition), class: "btn btn-success btn-sm" %>

        <%= link_to 'Categorii', "#{entries_path}?from_competition_id=#{@competition.id}", class: "btn btn-success btn-sm" %>


<table class="table table-striped table-bordered table-hover" id="runners-table">
    <thead class="table-primary">
        <tr>
            <th scope="col" class="sortable" data-sort-by="id">
                <%= link_to 'FOS ID' %>
            </th>
            <th class="sortable" data-sort-by="runner">
                <%= link_to 'Nume' %>
            </th>
            <th class="sortable" data-sort-by="gender">
                <%= link_to 'Genul' %>
            </th>
            <th class="sortable" data-sort-by="dob">
                <%= link_to 'Data Nastere'%>
            </th>
            <th class="sortable" data-sort-by="club">
                <%= link_to 'Club' %>
            </th>
            <th class="sortable" data-sort-by="merge_runner_id">
                <%= link_to 'Alt Sportiv' %>
            </th>
            <th>
                Uneste
            </th>
        </tr>
    </thead>
    <tbody>
        <% @runners.each do |runner| %>
        <%= form_tag"#{merge_runner_path(runner)}?redirect=#{request.url}" do %>
        <tr>
            <td>
                <%= runner.id %>
            </td>
            <td>
                <%= "#{runner.runner_name} #{runner.surname}" %>
            </td>
            <td>
                <%= runner.gender %>
            </td>
            <td>
                <%= runner.dob.strftime("%d/%m/%Y") %>
            </td>
            <td>
                <%= link_to runner.club&.club_name, runner.club %>
            </td>
            <td>
                <%= select_tag :merge_runner_id, options_for_select((@all_runners - [runner]).sort_by { |runner| [runner.runner_name, runner.surname] }.map { |runner| ["#{runner.runner_name} #{runner.surname}", runner.id] }, params[:runner_id]), class: "custom-select" %>

            </td>
            <td>

                <%= image_submit_tag "/confirm.png", alt: "Approve", style: "width: 35px; height: 30px;" %>


            </td>

        </tr>
                <% end %>

        <% end %>
    </tbody>

</table>

app/views/competitions/pdf.html.erb
<%= render partial: 'results/results_table2', locals: { results: @competition.groups.first.results, show_pagination: false } %>

app/views/competitions/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<div class="mt-4 p-5 bg-light text-black rounded --bs-gray-500">
    <h1>
        <%= @competition.competition_name %>
    </h1>
    <% if admin_user? %>
    <div class="d-inline-block me-2">
        <div class="dropdown">
            <button class="btn-danger btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Exportă
            </button>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Exporta PDF', pdf_competition_path(@competition), class: "dropdown-item" %>
                </li>
                <li>
                    <%= link_to 'Exporta CSV', download_ecn_csv_competition_path(@competition), class: "dropdown-item" %>
                </li>
            </ul>
        </div>
    </div>
    <div class="d-inline-block">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Acțiuni
            </button>
            <ul class="dropdown-menu">
                <li>
                    <%= form_tag(set_ecn_competition_path, method: :post) do %>
                    <%= hidden_field_tag :id, @competition.id %>
                    <% text = @competition.ecn ? "Exclude din ECN" : "Adauga la ECN" %>
                    <%= submit_tag text, class: "dropdown-item" %>
                    <% end %>
                </li>
                <% if @competition.ecn %>
                <li>
                    <%= link_to 'Seteaza Coeficientii Grupelor', group_ecn_coeficients_competition_path(@competition), class: "dropdown-item" %>
                </li>
                <% end %>
                <% if @competition.wre_id %>
                    <li>
                        <%= link_to 'Calculeaza Wre Puncte',set_wre_categories_competition_path(@competition), class: "dropdown-item" %>
                    </li>
                <%else %>
                    <li>
                        <%= link_to 'Actualizeaza Clasele Grupelor', update_group_clasa_competition_path(@competition), class: "dropdown-item" %>
                    </li>
                <% end %>
                <li>
                    <%= link_to 'Sportivi noi', new_runners_competition_path(@competition), class: "dropdown-item" %>
                </li>
            </ul>
        </div>
    </div>
    <hr>
    <% end %>
    <p>
        <strong>Data:</strong>
        <%= @competition.date.strftime("%d/%m/%Y") %>
    </p>
    <p>
        <strong>Tipul Distantei</strong>
        <%= @competition.distance_type %>
    </p>
    <hr class="my-4">
    <p>
        <strong>Orasul</strong>
        <%= @competition.location%>
    </p>
    <p>
        <strong>Tara</strong>
        <%= @competition.country %>
    </p>
    <% if wre_id = @competition.wre_id %>
    <p>
        <strong>WRE ID</strong>
        <%= wre_id %>
    </p>
    <br>
    <% end %>
    <ul class="nav nav-pills">
        <% @competition.groups.order(:group_name).each_with_index do |group, index| %>
        <li class="nav-item">
            <a class="nav-link group-toogle<%= " active" if index.zero?%>" data-bs-toggle="pill" href="#menu<%=group.group_name %>"><%=group.group_name%></a>
        </li>
        <% end%>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <% @competition.groups.order(:group_name).each_with_index do |group, index| %>
        <div class="tab-pane container <%= index.zero? ? " active" : "fade" %>" id="menu<%=group.group_name %>">
            <%= render partial: 'groups/group_table', locals: { group: group} %>
        </div>
        <% end%>
    </div>
    <p class="lead">
        <% if admin_user? %>
        <%= link_to 'Editează', edit_polymorphic_path(@competition), class: "btn btn-success btn-sm" %>
        <%= link_to 'Șterge', @competition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        <% end %>
        <%= link_to 'Înapoi', request.referer, class: "btn btn-secondary btn-sm" %>
    </p>
</div>
<script>

$(document).ready(function() { $('a.nav-link.group-toogle:first').tab('show');});

$(document).ready(function() {
    $('.group-toogle').on('click', function(e) {
        e.preventDefault(); // Prevent the default behavior of the link

        var group = $(this).text();
        var currentUrl = new URL(window.location.href);
        currentUrl.searchParams.set('group', group);
        window.history.replaceState({}, '', currentUrl);
    });
});
</script>