config/routes.rb
Rails.application.routes.draw do
  resources :relay_results
  resources :entries do
    member do
      patch :confirm
      delete :reject
      patch :pending
    end
  end
  post 'results/from_competition'
  resources :results
  get 'runners/license'
  get 'runners/update_profile', to: 'runners#update_profile'

  resources :runners do
    collection do
      post 'license'
    end

    member do
      post :merge
    end
  end
  resources :clubs do
       member do
      post :merge
    end
  end

  get 'categories/expired', to: 'categories#expired'
  resources :categories

  get 'groups/pdf'

  resources :groups
  devise_for :users
  get 'competitions/ecn_ranking'
  resources :competitions do
    member do
      get 'pdf', to: 'competitions#pdf'
      get 'group_clasa', to: 'competitions#group_clasa'
      get 'new_runners', to: 'competitions#new_runners'
      post 'set_ecn', as: 'set_ecn'
      get 'group_ecn_coeficients', to: 'competitions#group_ecn_coeficients'
      post 'group_ecn_coeficients', to: 'competitions#update_group_ecn_coeficients', as: 'update_group_ecn_coeficients'
      post 'group_clasa', to: 'competitions#update_group_clasa', as: 'update_group_clasa'
      get 'ecn_csv', to: 'competitions#ecn_csv', as: 'download_ecn_csv'
      get 'set_wre_categories', to: 'competitions#set_wre_categories', as: 'set_wre_categories'
    end
  end

  get 'home/index'
  post 'result/modal_new', to: 'results#modal_new', as: "modal_result"

  root "home#index"
  get 'parser/index', as: "parser"
  get 'parser/file_results', as: 'file_results'
  post 'parser/file_results'
  post 'parser/file_relay_results'
  post 'parser/runners_dob'
  get 'parser/iof_runners', as: 'iof_runners'
  get 'parser/iof_results', as: 'iof_results'
  get 'parser/fos_data', as: 'fos_data'
  get 'parser/sync_fos', as: 'sync_fos'
  post 'groups/count_rang', as: 'count_rang'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @clubs_count        = Club.count
    @runners_count      = Runner.count
    @competitions_count = Competition.count
    @results_count      = Result.count

    @competitions = Competition.order(date: :desc).limit(10)
  end
end

app/views/home/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light" style="background-color: #85de6a;">
    <div class="container-fluid">
           <%= link_to image_tag(asset_pack_path('media/images/logo_fos.png'), class: "header-logo"), root_path, class: "logo nav-link" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Baza de Date
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%=link_to "Cluburi",     clubs_path,        class: "dropdown-item" %>
                        <%=link_to "Sportivi",    runners_path,      class: "dropdown-item" %>
                        <%=link_to "Competitii",  competitions_path, class: "dropdown-item" %>
                        <%=link_to "Grupe",       groups_path,       class: "dropdown-item" %>
                        <%=link_to "Rezultate",   results_path,      class: "dropdown-item" %>
                        <%=link_to "Indepliniri", entries_path,      class: "dropdown-item" %>
                        <%=link_to "Categorii",   categories_path,   class: "dropdown-item" %>
                        <%=link_to "Clasament National",   competitions_ecn_ranking_path,   class: "dropdown-item" %>
                        <%=link_to "Licențe",   runners_license_path,   class: "dropdown-item" %>
                    </ul>
                </li>
                <% if admin_user? || club_admin?%>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Adauga la Baza de Date
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <% if admin_user? %>
                        <%=link_to "Adauga Club",                    new_club_path,        class: "dropdown-item" %>
                        <% end %>
                        <%=link_to "Adauga Sportiv",    new_runner_path,      class: "dropdown-item" %>
                        <%=link_to "Adauga Competitie", new_competition_path, class: "dropdown-item" %>
                        <%=link_to "Adauga Grupa",      new_group_path,       class: "dropdown-item" %>
                        <%=link_to "Adauga Rezultat",   new_result_path,      class: "dropdown-item" %>
                        <% if admin_user? %>
                        <%=link_to "Adauga Din Fisier", file_results_path,      class: "dropdown-item" %>
                        <% end %>
                    </ul>
                </li>
                <% end %>
                <% if admin_user? %>
                <li class="nav-item">
                    <%=link_to "Actualizează datele", parser_path, class: "nav-link" %>
                </li>
                 <% end %>
                    <li class="nav-item">
                    </li>
            </ul>
            <div class="col-md-3 text-end">
                <% if user_signed_in? %>
                <%=link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-primary" %>
                <%=link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
                <% else %>
                <%=link_to 'Sign Up', new_user_registration_path, class: "btn btn-success me-2" %>
                <%=link_to 'Sign In', new_user_session_path, class: "btn btn-info" %>
                <% end %>
            </div>
        </div>
    </div>
</header>

app/views/home/index.html.erb
<h1>Bine ați venit în baza de date a orientării sportive</h1>

<table class="table table-bordered ">
  <thead>
    <tr class = "table-primary">
      <th scope="col">Sportivi</th>
      <th scope="col">Cluburi</th>
      <th scope="col">Rezultate</th>
      <th scope="col">Competiții</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%=link_to "#{@runners_count}", runners_path %></td>
      <td><%=link_to "#{@clubs_count}", clubs_path %></td>
      <td><%=link_to "#{@results_count}", results_path %></td>
      <td><%=link_to "#{@competitions_count}", competitions_path %></td>
    </tr>
  </tbody>
</table>

<h1> Ultimele 10 Competiții</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-primary">
     <tr>
      <th scope="col"> <%= link_to 'Data', sort: "date" %></th>
      <th><%= link_to 'Nume', sort: "competition_name"%></th>
      <th><%= link_to 'Oras', sort: "location" %></th>
      <th><%= link_to 'Tara', sort: "country" %></th>
      <th><%= link_to 'Tipul distantei', sort: "distance_type" %></th>
      <th><%= link_to 'Wre ID', sort: "wre_id" %></th>
      <th colspan="3">Acțiuni</th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.date %></td>
        <td><%= competition.competition_name %></td>
        <td><%= competition.location %></td>
        <td><%= competition.country %></td>
        <td><%= competition.distance_type %></td>
        <td><%= competition.wre_id %></td>
        <td><%= link_to 'Arată', competition, class: "btn btn-warning btn-sm"%></td>
        <% if admin_user? %>
          <td><%= link_to 'Editează', edit_polymorphic_path(competition), class: "btn btn-success btn-sm"%></td>
          <td><%= link_to 'Șterge', competition, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>