config/routes.rb
Rails.application.routes.draw do
  resources :relay_results
  resources :entries do
    member do
      patch :confirm
      delete :reject
      patch :pending
    end
  end
  post 'results/from_competition'
  resources :results
  get 'runners/license'
  get 'runners/update_profile', to: 'runners#update_profile'

  resources :runners do
    collection do
      post 'license'
    end

    member do
      post :merge
    end
  end
  resources :clubs do
       member do
      post :merge
    end
  end

  get 'categories/expired', to: 'categories#expired'
  resources :categories

  get 'groups/pdf'

  resources :groups
  devise_for :users
  get 'competitions/ecn_ranking'
  resources :competitions do
    member do
      get 'pdf', to: 'competitions#pdf'
      get 'group_clasa', to: 'competitions#group_clasa'
      get 'new_runners', to: 'competitions#new_runners'
      post 'set_ecn', as: 'set_ecn'
      get 'group_ecn_coeficients', to: 'competitions#group_ecn_coeficients'
      post 'group_ecn_coeficients', to: 'competitions#update_group_ecn_coeficients', as: 'update_group_ecn_coeficients'
      post 'group_clasa', to: 'competitions#update_group_clasa', as: 'update_group_clasa'
      get 'ecn_csv', to: 'competitions#ecn_csv', as: 'download_ecn_csv'
      get 'set_wre_categories', to: 'competitions#set_wre_categories', as: 'set_wre_categories'
    end
  end

  get 'home/index'
  post 'result/modal_new', to: 'results#modal_new', as: "modal_result"

  root "home#index"
  get 'parser/index', as: "parser"
  get 'parser/file_results', as: 'file_results'
  post 'parser/file_results'
  post 'parser/file_relay_results'
  post 'parser/runners_dob'
  get 'parser/iof_runners', as: 'iof_runners'
  get 'parser/iof_results', as: 'iof_results'
  get 'parser/fos_data', as: 'fos_data'
  get 'parser/sync_fos', as: 'sync_fos'
  post 'groups/count_rang', as: 'count_rang'
end

app/models/result.rb
class Result < ApplicationRecord
  attr_accessor :status
  belongs_to :runner
  belongs_to :category
  belongs_to :group
  has_one :entry, dependent: :destroy

  accepts_nested_attributes_for :group

  before_save :add_date
  scope :runner_id,      ->(runner_id) { where runner_id: runner_id}
  scope :group_id,      ->(group_id) { where group_id: group_id}
  scope :competition_id, ->(competition_id) { joins(:group).where('group.competition_id' => competition_id) }
  scope :category_id,    ->(category_id) { where category_id: }
  scope :date,           ->(from, to) { where date: from..to }
  scope :wre,            -> { where('wre_points > 0') }
  scope :sorting,        lambda { |sort_by, direction|
    case sort_by
    when 'runner_name'
      joins(:runner).order('runner_name' => direction, 'surname' => direction)
    when 'competition_name'
      joins(group: :competition).order("competitions.competition_name #{direction}")
    when 'group_name'
      joins(:group).order("groups.group_name #{direction}")
    when 'current_category_id'
      select("results.*, (SELECT entries.category_id FROM entries WHERE entries.runner_id = results.runner_id AND entries.status = #{Entry::CONFIRMED} AND entries.date < results.date ORDER BY entries.date DESC LIMIT 1) AS cat_id")
                       .order("cat_id #{direction}")
    else
      order("#{sort_by} #{direction}")
    end
  }

  private

  def add_date
    return if date

    self.date = group.competition.date
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: %i[show edit update destroy]

  has_scope :runner_id
  has_scope :competition_id
  has_scope :category_id
  has_scope :wre, type: :boolean
  has_scope :date, using: %i[from to], type: :hash

  # GET /results or /results.json
  def index
    @results = filter_results(params.to_unsafe_h)
    @results = @results.paginate(page: params[:page], per_page: 20)
  end

  # GET /results/1 or /results/1.json
  def show; end

  # GET /results/new
  def new
    @result = Result.new
  end

  def modal_new
    params_hash = params.to_unsafe_h.except('authenticity_token', 'controller', 'action', 'runner').to_hash
    redis = Redis.new(url: ENV['REDIS_URL'], ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE })

    redis.hset('new_res', params['runner']['uuid'], params_hash.to_json)

    respond_to do |format|
      format.js { render 'close_modal' }
    end
  end

  # GET /results/1/edit
  def edit; end

  # POST /results or /results.json
  def create
    respond_to do |format|
      parser = ResultFormParser.new(result_params)
      @result = parser.convert

      format.html { redirect_to result_url(@result), notice: 'Result was successfully created.' }
      format.json { render :show, status: :created, location: @result }
    end
  end

  # PATCH/PUT /results/1 or /results/1.json
  def update
    respond_to do |format|
      if ResultAndEntryProcessor.new(params_for_results.to_h, @result).update_result
        request.referer[/\/competitions\/\d+/]
        format.html do
          redirect_uri = request.referer[/\/competitions\/\d+/] ? request.referer : result_url(@result)
          redirect_to redirect_uri, notice: 'Result was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1 or /results/1.json
  def destroy
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def from_competition
    result_time = convert_time(result_params[:time])
    result = ResultAndEntryProcessor.new(result_params.except(:time).merge(time: result_time).to_h).add_result
    redirect_to "#{request.referer}#menu#{result.group.group_name}"

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_result
    @result = Result.find(params[:id])
  end

  def params_for_results
    res_params = result_params

    if %w[0 1].include?(res_params.dig('group_attributes', 'competition_id'))
      res_params['group_id'] = res_params.dig('group_attributes', 'competition_id')
      res_params.delete('group_attributes')
    else
      res_params.delete('date')
    end

    res_params.delete('group_attributes') unless res_params.dig('group_attributes', 'group_name')
    res_params["time"] = convert_time(res_params["time"])
    res_params
  end

  # Only allow a list of trusted parameters through.
  def result_params
    params.require(:result).permit(:place, :runner_id, :time, :category_id, :group_id, :wre_points, :ecn_points, :date,
                                   group_attributes: [:id, :group_name, :competition_id, { competition_attributes: %i[id competition_name date location country distance_type wre_id] }])
  end

    def convert_time(string)
    return string unless string[/:|\.|,/]

    seconds, minutes, hours = string.split(/:|\.|,/).map(&:to_i).reverse

    (hours || 0) * 3600 + minutes * 60 + seconds
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def filter_results(params)
    params = params.with_indifferent_access
    results = Result.order(date: :desc).includes(runner: [entries: :category], category: [], group: { competition: [] })
    # results = results.order(date: :desc) unless params[:sort_by]

    filtering_params = params.slice(:runner_id, :group_id, :competition_id, :category_id, :wre, :sort_by, :date)

    filtering_params.each do |key, value|
      next if value.blank?
      results = case key
      when "wre"     then results.wre
      when "sort_by" then results.sorting(value, params[:direction])
      when "date"     then results.date(value[:from].presence, value[:to].presence)
      else results.public_send(key, value)
      end
    end

    results
  end
end

app/views/results/_form.html.erb
<% if admin_user? %>
<%= form_with(model: result) do |form| %>
<% if result.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>
    <ul>
        <% result.errors.each do |error| %>
        <li>
            <%= error.full_message %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="row">
    <%= form.fields_for :group_attributes do |form_group| %>
    <%= render 'results_script', form_group: form_group, form: form %>
    <div class="col">
        <%= form_group.label :competition_id ,'Competitia'%>
        <%= form_group.select :competition_id,  options_for_select(Competition.all.map { |comp| [comp.competition_name, comp.id] } + [["Competitie Noua", nil]], selected: result&.group&.competition_id || 3), {},{class: "form-select form-group form-control"} %>
    </div>
    <div class="col" id="group-data">
    </div>
</div>
<br>
<div id="new-competition"></div>
<br>
<% end %>
<div class="row">
    <div class="col">
        <%= form.select :runner_id, options_for_select(Runner.order(:runner_name, :surname).map { |runner| ["#{runner.runner_name} #{runner.surname}", runner.id] }, selected: result&.runner_id), {}, { class: "form-select form-group form-control" } %>
    </div>
    <div class="col">
        <%= form.select :category_id,  options_for_select(Category.all.map { |category| [category.category_name, category.id] },selected: result&.category_id), {},{class: "form-select form-group form-control"} %>
    </div>
    <div class="col">
        <%= form.number_field :wre_points, placeholder: "WRE Puncte", class: "form-control"  %>
    </div>
</div>
<br>
<div id="result-details" style="display:none">
    <div class="row">
        <div class="col">
            <%= form.number_field :place, placeholder: "Locul", class: "form-control"  %>
        </div>
        <div class="col" style="display:none">
            <%= form.number_field :time, placeholder: "Timpul", class: "form-control" %>
        </div>
        <div class="col">
            <%= number_field_tag :hours, nil,  placeholder: "Ore", class: "form-control" %>
        </div>
        <div class="col">
            <%= number_field_tag :minutes, nil, placeholder: "Minute", class: "form-control"  %>
        </div>
        <div class="col">
            <%= number_field_tag :seconds, nil, placeholder: "Secunde", class: "form-control"  %>
        </div>
    </div>
</div>
<div id="date-details">
    <div class="row">
        <div class="col">
            <%= form.label :date ,'Data'%>
            <%= form.date_select :date, {order: [:day, :month, :year], use_month_numbers: true, end_year: Date.today.year, start_year: 2015 } , class: "date-select" %>
        </div>
    </div>
</div>
<br>
<div class="actions">
    <%= form.submit class: "btn btn-success btn-sm"%>
    <%= link_to 'Inapoi', request.referer, class: "btn btn-secondary btn-sm" %>
</div>
<% end %>
<% else %>
<h3> Doar administratorul poate adăuga rezultat </h3>
<% end %>

app/views/results/_form2.html.erb
<%= form_with url: modal_result_path, method: :post, remote: true, id: 'modal-form' do |form| %>


<div class="row">
    <%= form.fields_for :group_attributes do |form_group| %>
    <%= render partial: 'results/results_script', locals: { form_group: form_group, form: form } %>


    <div class="col">
        <%= form_group.label :competition_id ,'Competitia'%>
        <%= form_group.select :competition_id,  options_for_select(Competition.all.map { |comp| [comp.competition_name, comp.id] } + [["Competitie Noua", nil]], selected: result&.group&.competition_id || 1), {},{class: "form-select form-group form-control",  onChange: "competitionChange()"} %>
    </div>
    <div class="col" id="group-data">
    </div>
</div>
<br>
<div id="new-competition"></div>
<br>
<% end %>
<div id="result-details" style="display:none">
    <div class="row">
        <div class="col">
            <%= form.number_field :place, placeholder: "Locul", class: "form-control"  %>
        </div>

        <div class="col">
            <%= form.number_field :wre_points, placeholder: "WRE Puncte", class: "form-control"  %>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col" style="display:none">
            <%= form.number_field :time, placeholder: "Timpul", class: "form-control" %>
        </div>
        <div class="col">
            <%= number_field_tag :hours, nil,  placeholder: "Ore", class: "form-control" %>
        </div>
        <div class="col">
            <%= number_field_tag :minutes, nil, placeholder: "Minute", class: "form-control"  %>
        </div>
        <div class="col">
            <%= number_field_tag :seconds, nil, placeholder: "Secunde", class: "form-control"  %>
        </div>
    </div>
</div>
<div id="date-details">
    <div class="row">
        <div class="col">
            <%= form.label :date ,'Data'%>
            <%= form.date_select :date, {order: [:day, :month, :year], use_month_numbers: true, end_year: Date.today.year, start_year: 2015 } , class: "date-select" %>
        </div>
    </div>
</div>
<br>
 <div class="actions">
    <%= form.submit "Adaugă", class: "btn btn-success btn-sm"%>

    <%= link_to 'Inapoi', request.referer, class: "btn btn-secondary btn-sm" %>
</div>
<% end %>

app/views/results/_relay_results_table.html.erb
<% group_id ||= nil %>
<table class="table table-bordered table-hover" id="results-table">
   <thead class="table-primary">
        <tr>
            <th scope="col">
                <%= link_to 'Locul' %>
            </th>
            <th colspan="2">
                <%= link_to 'Echipa'%>
            </th>
            <th colspan="2">
                <%= link_to 'Timpul'%>
            </th>
            <th>
                <%= link_to 'Categoria indeplinita' %>
            </th>
        </tr>
    </thead>

    <tbody>
        <% relay_results.order(:place).each do |relay_result| %>
        <tr>
            <td colspan="6"></td>
        </tr>
        <tr class="table-success">
            <td>
                <%= relay_result.place %>
            </td>
            <td colspan="2">
                <%= relay_result.team %>
            </td>
            <td colspan="2">
                <%= Time.at(relay_result.time).utc.strftime('%H:%M:%S') %>
            </td>
            <td>
            </td>
        </tr>
        <% total_time = 0 %>
        <%  relay_result.results_id.each_with_index do |result_id, index| %>
        <% result = Result.find(result_id) %>
        <tr>
            <td>Etapa
                <%= index + 1 %>
            </td>
            <td>
                <%= link_to "#{result.runner.runner_name} #{result.runner.surname}", result.runner  %>
            </td>
            <td>
                <% @default_category ||= Category.find(10) %>
                <%= (result.runner.entry_on_date(result.date)&.category || @default_category).category_name %>
            </td>
            <td>
                <%= Time.at(result.time).utc.strftime('%H:%M:%S') %>
            </td>
            <td>
                <% total_time += result.time %>
                <%= Time.at(total_time).utc.strftime('%H:%M:%S') %>
            </td>
            <td>
                <%= result.category.category_name %>
            </td>
        </tr>
        <% end %>
        <% end %>
    </tbody>
    </tbody>
</table>
<hr>

app/views/results/_results_filter.html.erb
<% path = case controller.class
when RunnersController then runner_path(runner)
else results_path
end %>
<%= form_tag path, method: :get, id: 'results_search_form' do %>
<% unless controller.class == RunnersController %>
<%= label_tag "runner_id", "Sportiv", class: "label-filter" %>
<%= select_tag :runner_id, options_for_select(Runner.order("runner_name", "surname").map { |runner| ["#{runner.runner_name} #{runner.surname}", runner.id] }, params[:runner_id]), include_blank: "Toti Sportivi", class: "custom-select" %>
<br>
<% end %>
<%= label_tag "competition_id", "Competitia", class: "label-filter" %>
<% competition_list = runner ? Competition.joins(groups: :results).where('results.id IN (?)', runner.results.map(&:id)) : Competition.all %>
<%= select_tag :competition_id, options_for_select(competition_list.map { |comp| ["#{comp.competition_name} #{comp.date.year} #{comp.distance_type}", comp.id] }, params[:competition_id]), include_blank: "Toate Competitiile", class: "custom-select" %>
<br>
<%= label_tag "category_id", "Categoria indeplinita", class: "label-filter" %>
<%= select_tag :category_id, options_for_select(Category.pluck(:category_name, :id), params[:category_id]), include_blank: "Toate Categoriile", class: "custom-select" %>
<br>
<%= label_tag "wre", "Doar Rezultate WRE",class: "label-filter" %>
<%= check_box_tag :wre, true, params[:wre], id: "wre" %>
<br>
<%= label_tag "date[from]", "Data: De la", class: "label-filter", for: "date[from]" %>
<%= text_field_tag "date[from]", params.dig("date","from"), id: "date[from]", placeholder: "zz/ll/aaaa", class: "datepicker custom-select" %>
<%= label_tag "date[to]", "Pina la", class: "label-filter", for: "date[to]" %>
<%= text_field_tag "date[to]", params.dig("date","to"), id: "date[to]", placeholder: "zz/ll/aaaa", class: "datepicker custom-select" %>
<br>
<%= submit_tag "Filtreaza", class: "btn btn-info" %>
<% end %>
<hr>

app/views/results/_results_script.html.erb
<script>
function showHideNewCompetition() {

  var value = $('[id*="competition_id"]').val();
  var html = "";


  if (value == "") {
    html = '<%= j render partial: "competitions/create_competition", locals: { form: form_group }  %>';
    addGroup("text_field");
  } else {
    addGroup("select");
  }

  $('#new-competition').html(html);
};


function addGroup(type) {
    var html = "";

    if (type == "text_field") {
        html = '<%=j form_group.label :group_name ,"Grupa"%><%= j form_group.text_field :group_name, placeholder: "Grupa", class: "form-control" %>';
    } else {
        html = '<%=j form.label :group_id ,"Grupa"%><%=j form.select :group_id,[], {},{class: "form-select form-group form-control", onChange: "showHideNewGroup()"} %>';
    }

    $('#group-data').replaceWith('<div class="col" id="group-data">' + html + '</div>');
}
</script>

app/views/results/_results_table.html.erb
<% group_id ||= nil %>
<table class="table table-striped table-bordered table-hover" id="results-table">
    <thead class="table-primary">
        <tr>
            <th scope="col" class="sortable" data-sort-by="place">
                <%= link_to 'Locul' %>
            </th>
            <% unless controller.class == RunnersController %>
            <th class="sortable" data-sort-by="runner_name">
                <%= link_to 'Sportiv'%>
            </th>
            <% end %>
            <th class="sortable" data-sort-by="current_category_id">
                <%= link_to 'Categoria actuală'%>
            </th>
            <th class="sortable" data-sort-by="time">
                <%= link_to 'Timpul' %>
            </th>
            <th class="sortable" data-sort-by="category_id">
                <%= link_to 'Categoria indeplinita' %>
            </th>
            <% unless [GroupsController, CompetitionsController].include?(controller.class)%>
            <th class="sortable" data-sort-by="date">
                <%= link_to 'Data' %>
            </th>
            <th class="sortable" data-sort-by="competition_name">
                <%= link_to 'Competitia' %>
            </th>
            <% end %>
            <% unless controller.class == RunnersController %>
            <th class="sortable" data-sort-by="group_name">
                <%= link_to 'Grupa' %>
            </th>
            <% end %>
            <th class="sortable" data-sort-by="wre_points">
                <%= link_to 'Wre Puncte' %>
            </th>
            <th class="sortable" data-sort-by="ecn_points">
                <%= link_to 'ECN Puncte' %>
            </th>
            <% if [CompetitionsController, ResultsController].include?(controller.class) %>
            <th colspan="3">Acțiuni</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% results.each do |result| %>
        <tr id="result_<%= result.id %>">
            <td>
                <%= result.place %>
            </td>
            <% unless controller.class == RunnersController %>
            <td>
                <%= link_to "#{result.runner.runner_name} #{result.runner.surname}", result.runner  %>
            </td>
            <% end %>
            <td>
                <% @default_category ||= Category.find(10) %>
                <%= (result.runner.entry_on_date(result.date)&.category || @default_category).category_name %>
            </td>
            <td>
                <%= Time.at(result.time).utc.strftime('%H:%M:%S') %>
            </td>
            <td>
                <%= result.category.category_name %>
            </td>
            <% unless [GroupsController, CompetitionsController].include?(controller.class)%>
            <td>
                <%= result.date %>
            </td>
            <td>
                <%= link_to "#{result.group.competition.competition_name} #{result.group.competition.date.year}", result.group.competition %>
            </td>
            <% end %>
            <% unless controller.class == RunnersController %>
            <td>
                <%= link_to result.group.group_name, result.group %>
            </td>
            <% end %>
            <td>
                <%= result.wre_points %>
            </td>
            <td>
                <%= result.ecn_points %>
            </td>
            <% if [CompetitionsController, ResultsController].include?(controller.class) %>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <%= link_to 'Arată', result, class: "btn btn-warning btn-sm"%>
                    <% if admin_user? %>
                    <%= button_tag 'Editează', onclick: "show_hide_form_result('#edit_result_#{result.id}', '#result_#{result.id}')", class: "btn btn-success btn-sm" %>

                    <%= link_to 'Șterge', result, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                    <% end %>
                </div>
            </td>
            <% end %>
        </tr>
        <tr id="edit_result_<%= result.id %>" style="display: none;">
            <%= form_with(model: result, url: result_path(result), method: :patch, local: true) do |form| %>
            <td>
                <%= form.number_field :place, value: result.place, step: 1, min: 1, placeholder: "Locul", class: "form-control"  %>
            </td>
            <td>
                <%= form.select :runner_id, options_for_select(Runner.order(:runner_name, :surname).map { |runner| ["#{runner.runner_name} #{runner.surname}", runner.id] }, selected: result&.runner_id), {}, { class: "form-select form-group form-control" } %>
            </td>
            <td></td>
            <td>
                <%= form.text_field :time, value:  Time.at(result.time).utc.strftime("%H:%M:%S") ,placeholder: "hh:mm:ss", class: "form-control" %>
            </td>
            <td>
                <%= form.select :category_id,  options_for_select(Category.all.map { |category| [category.category_name, category.id] }, selected: result&.category_id), {},{class: "form-select form-group form-control"} %>
            </td>
            <td>
                <%= form.hidden_field :group_id, value: group_id %>
            </td>
            <td>
                <%= form.number_field :wre_points, value: result.wre_points %>
            </td>
                        <td>
                <%= form.text_field :ecn_points, value: result.ecn_points %>
            </td>
            <td>
               <button type="submit" style="border: none; background: none;">
            <%= image_tag("/confirm.png", alt: "Actualizeaza Rezultat", size: "35x30" ) %>
          </button>
            <% end %>
            <%= image_tag "/reject.jpeg", alt: "Hide", size: "30x30", onclick: "show_hide_form_result('#result_#{result.id}', '#edit_result_#{result.id}')" %></td>
        </tr>
        <% end %>
        <% if admin_user? && group_id %>
        <tr style="display: none" id="new_result_row_<%= group_id %>">
            <%= form_with(model: Result.new, url: results_from_competition_path, local: true) do |form| %>
            <td>
                <%= form.number_field :place, step: 1, min: 1, placeholder: "Locul", value: ((Group.find(group_id).results.pluck(:place).map(&:to_i).max || 0) +1), class: "form-control"  %>
            </td>
            <td>
                <%= form.select :runner_id, options_for_select(Runner.order(:runner_name, :surname).map { |runner| ["#{runner.runner_name} #{runner.surname}", runner.id] }), {}, { class: "form-select form-group form-control" } %>
            </td>
            <td></td>
            <td>
                <%= form.text_field :time, placeholder: "hh:mm:ss", class: "form-control" %>
            </td>
            <td>
                <%= form.select :category_id,  options_for_select(Category.all.map { |category| [category.category_name, category.id] }, selected: 10), {},{class: "form-select form-group form-control"} %>
            </td>
            <td>
                <%= form.hidden_field :group_id, value: group_id %>
            </td>
            <td>
               <button type="submit" style="border: none; background: none;">
            <%= image_tag("/confirm.png", alt: "Adaugă Rezultat", size: "35x30" ) %>
          </button>
            </td>
            <% end %>
            <td><%= image_tag "/reject.jpeg", alt: "Hide", size: "30x30", onclick: "show_hide_form_result('#new_result_#{group_id}', '#new_result_row_#{group_id}')" %></td>
        </tr>
        <% end %>

    </tbody>
    <% if show_pagination %>
    <div class="pagination">
        <%= will_paginate results, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
    <% end %>
</table>
<% if admin_user? && group_id %>
<button type="button" class="btn btn-secondary" id="new_result_<%= group_id %>" onclick="show_hide_form_result('#new_result_row_<%= group_id %>', this)">New result</button>
<hr>
<% end %>
<script>
    function show_hide_form_result(showSelector, hideSelector) {
         var show_el = $(showSelector);
        var hide_el = $(hideSelector);

        show_el.show();
        hide_el.hide();
    }

    function hide_form_result() {
        $("#new_result_row").hide();
        $("#new_result").show();
    }

</script>

app/views/results/_results_table2.html.erb
<meta charset="UTF-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
 <h2><%= group.group_name %></h2>
<table class="table table-striped table-bordered table-hover" id="results-table">
    <thead class="table-primary">
        <tr>
            <th scope="col" class="sortable" data-sort-by="place">
               Locul
            </th>
            <th class="sortable" data-sort-by="runner_name">
                Sportiv
            </th>
            <th class="sortable" data-sort-by="fos_id">
                FOS ID
            </th>
            <th class="sortable" data-sort-by="current_category_id">
                Categoria actuală
            </th>
            <th class="sortable" data-sort-by="time">
                Timpul
            </th>
            <th class="sortable" data-sort-by="category_id">
               Categoria indeplinita
            </th>
            <th class="sortable" data-sort-by="ecn_points">
                ECN Puncte
            </th>
        </tr>
    </thead>
    <tbody>
        <% group.results.order(:place).each do |result| %>
        <tr>
            <td>
                <%= result.place %>
            </td>
            <td>
               <%=  "#{result.runner.runner_name} #{result.runner.surname}" %>
            </td>
                   <td>
               <%=  result.runner.id %>
            </td>
            <td>
                <% @default_category ||= Category.find(10) %>
                <%= (result.runner.entry_on_date(result.date)&.category || @default_category).category_name %>
            </td>
            <td>
                <%= Time.at(result.time).utc.strftime('%H:%M:%S') %>
            </td>
            <td>
                <%= result.category.category_name %>
            </td>

            <td>
                <%= result.ecn_points %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

 <hr>
            <% if group.rang %>
            <%  percent_and_time_data = GroupCategoriesUpdater.new(group).get_percent_and_times %>

            <br>
            <div class="half-width-table">
                <table class="table table-striped table-bordered table-hover">
                    <thead class="table-warning">
                        <tr>
                            <th scope="col"> Categoria
                            </th>
                            <th> Procente
                            </th>
                            <th> Timpul
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% percent_and_time_data.each do |cat| %>
                        <tr>
                            <td>
                                <%= cat[:category] %>
                            </td>
                            <td>
                                <%= "#{cat[:percent]} %" %>
                            </td>
                            <td>
                                <%= cat[:time] %>
                            </td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
            <div>Rang: <%= group.rang %> </div>
                        <% end %>
            <div>Clasa: <%= group.clasa.to_s[/\d{1,2}/] ? Category.find(group.clasa.to_i).category_name : group.clasa%> </div>

app/views/results/close_modal.js.erb
$('#myModal').modal('hide');

app/views/results/edit.html.erb
<h1>Editing Result</h1>
<script>
  $(document).ready(function() {
    setTime();
});
</script>

<%= render 'form', result: @result %>
<iframe onload="editPageLoad()">

app/views/results/index.html.erb
<p id="notice">
    <%= notice %>
</p>
<h1 style="text-align:center; color:green">Rezultate</h1>
<%= render partial: 'results_filter', locals: { runner: nil } %>
<%= render partial: 'results_table', locals: { results: @results, show_pagination: true } %>
<br>
<% if admin_user? || club_admin? %>
<%= link_to 'Rezultat Nou', new_result_path, class: "btn btn-info" %>
<% end %>

app/views/results/new.html.erb
<h1>Rezultat Nou</h1>

<%= render 'form', result: @result %>