config/routes.rb
Rails.application.routes.draw do
  resources :relay_results
  resources :entries do
    member do
      patch :confirm
      delete :reject
      patch :pending
    end
  end
  post 'results/from_competition'
  resources :results
  get 'runners/license'
  get 'runners/update_profile', to: 'runners#update_profile'

  resources :runners do
    collection do
      post 'license'
    end

    member do
      post :merge
    end
  end
  resources :clubs do
       member do
      post :merge
    end
  end

  get 'categories/expired', to: 'categories#expired'
  resources :categories

  get 'groups/pdf'

  resources :groups
  devise_for :users
  get 'competitions/ecn_ranking'
  resources :competitions do
    member do
      get 'pdf', to: 'competitions#pdf'
      get 'group_clasa', to: 'competitions#group_clasa'
      get 'new_runners', to: 'competitions#new_runners'
      post 'set_ecn', as: 'set_ecn'
      get 'group_ecn_coeficients', to: 'competitions#group_ecn_coeficients'
      post 'group_ecn_coeficients', to: 'competitions#update_group_ecn_coeficients', as: 'update_group_ecn_coeficients'
      post 'group_clasa', to: 'competitions#update_group_clasa', as: 'update_group_clasa'
      get 'ecn_csv', to: 'competitions#ecn_csv', as: 'download_ecn_csv'
      get 'set_wre_categories', to: 'competitions#set_wre_categories', as: 'set_wre_categories'
    end
  end

  get 'home/index'
  post 'result/modal_new', to: 'results#modal_new', as: "modal_result"

  root "home#index"
  get 'parser/index', as: "parser"
  get 'parser/file_results', as: 'file_results'
  post 'parser/file_results'
  post 'parser/file_relay_results'
  post 'parser/runners_dob'
  get 'parser/iof_runners', as: 'iof_runners'
  get 'parser/iof_results', as: 'iof_results'
  get 'parser/fos_data', as: 'fos_data'
  get 'parser/sync_fos', as: 'sync_fos'
  post 'groups/count_rang', as: 'count_rang'
end

app/controllers/parser_controller.rb
class ParserController < ApplicationController
  def index
  end

  def file_results
    return  redirect_to '/422.html' unless admin_user?

    return unless params[:path]

    respond_to do |format|
      path         = params[:path].tempfile.path

      parser = if params["relay"]
        RelayHtmlParser.new(path)
      elsif path[/json$/]
        JsonParser.new(path)
      elsif path[/html$/]
        HtmlParser.new(path)
      elsif  params[:path].headers[/competitie.+xlsx/]
        ExcelCompetitionParser.new(path)
      elsif params[:path].headers[/rezultate.+xlsx/]
        ExcelResultsParser.new(path)
      end
      @competition = parser.convert

      format.html { redirect_to competition_url(@competition), notice: 'Competitia a fost creata cu succes' }
    end
  end

   def runners_dob
    return  redirect_to '/422.html' unless admin_user?

    return unless params[:path]

    respond_to do |format|
      path = params[:path].tempfile.path

      RunnersParser.new(path).convert

      format.html { redirect_to file_results_url, notice: 'Competitia a fost creata cu succes' }
    end
  end

  def iof_runners
    return  redirect_to '/422.html' unless admin_user?

    respond_to do |format|
      IofRunnersJob.perform_later

      format.html { redirect_to "#{runners_url}?wre=true", notice: 'Datele wre despre sportivi au fost actualizate' }
    end
  end

  def iof_results
    return  redirect_to '/422.html' unless admin_user?

    respond_to do |format|
      IofResultsJob.perform_later

      format.html { redirect_to "#{competitions_url}?wre=true", notice: 'Datele wre despre sportivi au fost actualizate' }
    end
  end

  def fos_data
    return  redirect_to '/422.html' unless admin_user?

    respond_to do |format|
      parser = FosParser.new
      parser.convert

      format.html { redirect_to runners_url, notice: 'Datele  despre sportivi au fost extrase' }
    end
  end

  def sync_fos
    respond_to do |format|
      SyncFosJob.perform_later

      format.html { redirect_to runners_url, notice: 'Sincronizarea a inceput' }
    end
  end



end

app/views/parser/file_results.html.erb
<% if admin_user? %>
<%= form_tag file_results_path, multipart: true  do %>
  <%= file_field_tag :path %>
  <%= check_box_tag :relay, '1', false %>
  <%= label_tag :relay, "Stafeta?" %>
  <%= submit_tag "Încarcă", class: "btn btn-primary" %>
<% end %>

<%= form_tag parser_runners_dob_path, multipart: true  do %>
  <%= file_field_tag :path %>
  <%= submit_tag "Actualizeaza", class: "btn btn-primary" %>
<% end %>
<% else %>

<h3> Doar administratorul poate accesa aceasta pagina </h3>
<% end %>

app/views/parser/index.html.erb
<% if admin_user? %>

<%= link_to "WRE Ranking", iof_runners_path, class: "btn btn-primary" %>
<br>
<br>
<%= link_to "WRE Rezultate", iof_results_path, class: "btn btn-primary" %>
<br>
<br>
<%= link_to "FOS Date", fos_data_path, class: "btn btn-primary" %>
<br>
<br>
<%= link_to "Categorii Expirate", categories_expired_path, class: "btn btn-primary" %>
<br>
<br>
<%= link_to "Actualizeaza Profil Sportivi", runners_update_profile_path, class: "btn btn-primary" %>
<% else %>
<h3>Numai administratorul poate accesa aceasta pagina</h3>
<% end %>